export const AreaOptions: string[] = [
    "Direito Trabalhista",
    "Direito Previdenciário",
    "Direito Criminal",
    "Direito Empresarial",
    "Direito Ambiental",
    "Direito Civil",
    "Direito Constitucional",
    "Direito Administrativo",
    "Direito Tributário",
    "Direito de Família",
    "Direito do Consumidor",
    "Direito Imobiliário",
    "Direito Penal",
    "Direito Contratual",
    "Direito de Propriedade Intelectual",
    "Direito das Sociedades",
    "Direito de Propriedade",
    "Direito das Obrigações",
  ];
  export const ThemesOptions: any = {
    "Direito Trabalhista": [
      "Rescisões Contratuais",
      "Ações Trabalhistas (reclamações de direitos trabalhistas)",
      "Assédio no Local de Trabalho",
      "Discriminação no Trabalho",
      "Acidentes de Trabalho",
      "Atraso no Pagamento de Salários",
      "Horas Extras",
      "Insalubridade e Periculosidade",
      "Estabilidade no Emprego",
      "Férias e 13º Salário",
      "FGTS (Fundo de Garantia por Tempo de Serviço)",
      "Negociações Sindicais",
      "Terceirização Irregular",
      "Rescisão Indireta",
    ],
    "Direito Previdenciário": [
      "Aposentadoria por Idade",
      "Aposentadoria por Tempo de Contribuição",
      "Benefícios por Incapacidade (como auxílio-doença e aposentadoria por invalidez)",
      "Pensão por Morte",
      "Auxílio-Reclusão",
      "Revisões de Benefícios Previdenciários",
      "LOAS (Lei Orgânica de Assistência Social)",
      "Desaposentação",
      "Contribuições Previdenciárias em Atraso",
      "Tempo Rural",
      "Salário Maternidade",
      "Salário Família",
      "Reabilitação Profissional",
    ],
    "Direito Criminal": [
      "Homicídio",
      "Roubo",
      "Latrocínio",
      "Tráfico de Drogas",
      "Violência Doméstica",
      "Furto",
      "Lesão Corporal",
      "Estupro",
      "Crime de Trânsito",
      "Crimes contra a Administração Pública",
      "Crimes de Internet (como difamação online)",
      "Associação Criminosa",
      "Crimes Ambientais",
      "Crimes de Menor Potencial Ofensivo (como lesão leve)",
      "Crimes de Uso de Documento Falso",
    ],
    "Direito Empresarial": [
      "Contratos Empresariais",
      "Falência e Recuperação Judicial",
      "Sociedades Empresariais",
      "Propriedade Intelectual (marcas, patentes, direitos autorais)",
      "Concorrência Desleal",
      "Recuperação de Crédito",
      "Arbitragem Empresarial",
      "Responsabilidade de Administradores",
      "Compliance Empresarial",
      "Fusões e Aquisições (M&A)",
      "Direito Societário",
      "Contratos de Trabalho Empresariais",
      "Tributação de Empresas",
      "Litígios Contratuais Empresariais",
    ],
    "Direito Ambiental": [
      "Licenciamento Ambiental",
      "Responsabilidade Ambiental",
      "Conservação da Natureza",
      "Poluição Ambiental",
      "Direito Internacional Ambiental",
    ],
    "Direito Civil": [
      "Divórcio",
      "Guarda de Filhos",
      "Inventário e Partilha",
      "Ações de Cobrança",
      "Responsabilidade Civil (casos de danos a terceiros)",
      "Contratos (litígios contratuais)",
      "Despejo (para locações)",
      "Revisão de Alimentos",
      "Ações de Indenização",
      "Usucapião (casos de posse de imóveis)",
      "Adoção",
      "Investigação de Paternidade",
      "Ações de Danos Morais",
      "Revisionais de Contratos Bancários",
      "Direito do Consumidor (problemas com produtos ou serviços)",
    ],
    "Direito Constitucional": [
      "Ações Diretas de Inconstitucionalidade (ADIs)",
      "Ações Declaratórias de Constitucionalidade (ADCs)",
      "Mandado de Segurança",
      "Habeas Corpus",
      "Controle de Constitucionalidade",
    ],
    "Direito Administrativo": [
      "Licitações e Contratos Administrativos",
      "Improbidade Administrativa",
      "Processos Disciplinares de Servidores Públicos",
      "Concessões e Permissões de Serviços Públicos",
      "Atos Administrativos",
    ],
    "Direito Internacional": [
      "Tratados e Acordos Internacionais",
      "Imunidades Diplomáticas",
      "Direitos Humanos Internacionais",
      "Resolução de Conflitos Internacionais",
    ],
    "Direito Tributário": [
      "Impostos e Tributos (como Imposto de Renda e ICMS)",
      "Planejamento Tributário",
      "Contencioso Tributário",
      "Refis (Programa de Recuperação Fiscal)",
      "Isenções e Incentivos Fiscais",
    ],
    "Direito de Família": [
      "Divórcio",
      "Guarda de Filhos",
      "Pensão Alimentícia",
      "Partilha de Bens em Casos de Divórcio",
      "Regulamentação de Visitas",
    ],
    "Direito do Consumidor": [
      "Responsabilidade do Fornecedor",
      "Garantias de Produtos",
      "Práticas Abusivas",
      "Direito de Arrependimento",
      "Cobranças Indevidas",
    ],
    "Direito Imobiliário": [
      "Compra e Venda de Imóveis",
      "Locações e Despejos",
      "Regularização de Imóveis",
      "Financiamentos Imobiliários",
      "Usucapião",
    ],
    "Direito Penal": [
      "Crimes contra a Pessoa",
      "Crimes contra o Patrimônio",
      "Crimes contra a Liberdade Sexual",
      "Crimes contra a Administração Pública",
      "Prisão Preventiva",
    ],
    "Direito Contratual": [
      "Elaboração e Revisão de Contratos",
      "Descumprimento de Contratos",
      "Rescisão Contratual",
      "Cláusulas Contratuais Abusivas",
    ],
    "Direito de Propriedade Intelectual": [
      "Registro de Marcas e Patentes",
      "Direitos Autorais",
      "Contrafação (Pirataria)",
      "Proteção de Segredos Comerciais",
    ],
    "Direito das Sociedades": [
      "Constituição de Sociedades",
      "Fusões e Aquisições",
      "Governança Corporativa",
      "Dissolução de Sociedades",
    ],
    "Direito de Propriedade": [
      "Compra e Venda de Bens Móveis e Imóveis",
      "Usucapião",
      "Registros de Propriedade",
    ],
    "Direito das Obrigações": [
      "Obrigações Contratuais",
      "Enriquecimento Sem Causa",
      "Responsabilidade Civil Extracontratual",
    ],
  };
  
  export const InterestOptions: string[] = [
    'Criar uma petição',
    'Criar um Contrato',
    'Outros(Em Breve)',
  ]
  